### ISSUE TITLE
how to use it :-(

### ISSUE THREAD

**Issue by aliunco** [Loopersgroup/PersianIonicDatepicker#17]
Thank you so much for converting this calendar, would you please guild me to how to use your calendar and load the Shamsi style of this calendar?  🙏🏻

**Comment by amirtutunchi** [comment]
Hi @aliunco 
to use this component you should read the original repository for complete help(ionic datepicker) but for converting it to shamsi you need to change the variable lanq to true in your datepicker config and then you have the Persian date picker . BTW thanks for using it and we are going  to make a complete guide for it as soon as posible

**Comment by meysammahfouzi** [comment]
Using the ionic's datepicker is as simply as using the following markup:

`<ion-datetime displayFormat="h:mm A" pickerFormat="h mm A" [(ngModel)]="event.timeStarts">
</ion-datetime>`

What about your component? I am very much interested in using the Persian version of datepicker, but there is no guide whatsoever! Please!

**Comment by amirtutunchi** [comment]
use bower to install it
bower install loopersDatepicker
after that, you can follow the main rep we fork from https://www.npmjs.com/package/ionic-datepicker if you have more questions feel free to email me :)

**Comment by amirtutunchi** [comment]
we recently added a word file in the readme please use that for help
