### ISSUE TITLE
What about documentation? I really need it, But I don't know how to use it.

### ISSUE THREAD

**Issue by azad47808** [Loopersgroup/PersianIonicDatepicker#18]

**Comment by amirtutunchi** [comment]
use bower to install it 
bower install loopersDatepicker
after that, you can follow the main rep we fork from https://www.npmjs.com/package/ionic-datepicker if you have more questions feel free to email me :)

**Comment by amirtutunchi** [comment]
we recently added a word file in the readme please use that for help
